### ISSUE TITLE
TemplateSyntaxError on a monkey user trying to enter ballots

### ISSUE THREAD

**Issue by amrav** [czlee/tabbycat#268]
On the develop branch, a monkey user trying to enter ballots runs into the following error every single time. Superusers can enter ballots without any issue.

```
2016-01-25T09:54:46.431346+00:00 app[web.1]: Internal Server Error: /t/tpd12/admin/results/debate/14/new_ballotset/
2016-01-25T09:54:46.431350+00:00 app[web.1]: Traceback (most recent call last):
2016-01-25T09:54:46.431351+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 506, in parse
2016-01-25T09:54:46.431352+00:00 app[web.1]:     compile_func = self.tags[command]
2016-01-25T09:54:46.431353+00:00 app[web.1]: KeyError: 'static'
2016-01-25T09:54:46.431354+00:00 app[web.1]:
2016-01-25T09:54:46.431354+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2016-01-25T09:54:46.431355+00:00 app[web.1]:
2016-01-25T09:54:46.431355+00:00 app[web.1]: Traceback (most recent call last):
2016-01-25T09:54:46.431356+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
2016-01-25T09:54:46.431357+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)
2016-01-25T09:54:46.431358+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
2016-01-25T09:54:46.431374+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2016-01-25T09:54:46.431375+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
2016-01-25T09:54:46.431376+00:00 app[web.1]:     return view_func(request, *args, **kwargs)
2016-01-25T09:54:46.431377+00:00 app[web.1]:   File "/app/utils/views.py", line 25, in foo
2016-01-25T09:54:46.431377+00:00 app[web.1]:     return view_fn(request, request.tournament, *args, **kwargs)
2016-01-25T09:54:46.431378+00:00 app[web.1]:   File "/app/results/views.py", line 232, in new_ballotset
2016-01-25T09:54:46.431378+00:00 app[web.1]:     return r2r(request, template, context)
2016-01-25T09:54:46.431379+00:00 app[web.1]:   File "/app/utils/views.py", line 78, in r2r
2016-01-25T09:54:46.431380+00:00 app[web.1]:     return render_to_response(template, context_instance=rc)
2016-01-25T09:54:46.431380+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/shortcuts.py", line 45, in render_to_response
2016-01-25T09:54:46.431381+00:00 app[web.1]:     using=using)
2016-01-25T09:54:46.431382+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/loader.py", line 114, in render_to_string
2016-01-25T09:54:46.431382+00:00 app[web.1]:     template_name, context, context_instance, dirs, dictionary)
2016-01-25T09:54:46.431383+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/engine.py", line 231, in render_to_string
2016-01-25T09:54:46.431384+00:00 app[web.1]:     t = self.get_template(template_name, dirs)
2016-01-25T09:54:46.431384+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
2016-01-25T09:54:46.431385+00:00 app[web.1]:     template, origin = self.find_template(template_name, dirs)
2016-01-25T09:54:46.431386+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
2016-01-25T09:54:46.431386+00:00 app[web.1]:     name, template_dirs=dirs, skip=skip,
2016-01-25T09:54:46.431387+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/loaders/cached.py", line 39, in get_template
2016-01-25T09:54:46.431388+00:00 app[web.1]:     template_name, template_dirs, skip,
2016-01-25T09:54:46.431389+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
2016-01-25T09:54:46.431389+00:00 app[web.1]:     contents, origin, origin.template_name, self.engine,
2016-01-25T09:54:46.431390+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
2016-01-25T09:54:46.431391+00:00 app[web.1]:     self.nodelist = self.compile_nodelist()
2016-01-25T09:54:46.431391+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 230, in compile_nodelist
2016-01-25T09:54:46.431392+00:00 app[web.1]:     return parser.parse()
2016-01-25T09:54:46.431392+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
2016-01-25T09:54:46.431393+00:00 app[web.1]:     raise self.error(token, e)
2016-01-25T09:54:46.431394+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 512, in parse
2016-01-25T09:54:46.431394+00:00 app[web.1]:     compiled_result = compile_func(self, token)
2016-01-25T09:54:46.431395+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/loader_tags.py", line 267, in do_extends
2016-01-25T09:54:46.431396+00:00 app[web.1]:     nodelist = parser.parse()
2016-01-25T09:54:46.431396+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
2016-01-25T09:54:46.431397+00:00 app[web.1]:     raise self.error(token, e)
2016-01-25T09:54:46.431397+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 512, in parse
2016-01-25T09:54:46.431398+00:00 app[web.1]:     compiled_result = compile_func(self, token)
2016-01-25T09:54:46.431399+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/loader_tags.py", line 241, in do_block
2016-01-25T09:54:46.431399+00:00 app[web.1]:     nodelist = parser.parse(('endblock',))
2016-01-25T09:54:46.431400+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 508, in parse
2016-01-25T09:54:46.431401+00:00 app[web.1]:     self.invalid_block_tag(token, command, parse_until)
2016-01-25T09:54:46.431401+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 562, in invalid_block_tag
2016-01-25T09:54:46.431402+00:00 app[web.1]:     get_text_list(["'%s'" % p for p in parse_until]),
2016-01-25T09:54:46.431404+00:00 app[web.1]: django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 51: 'static', expected 'endblock'. Did you forget to register or load this tag?
2016-01-25T09:54:46.431410+00:00 app[web.1]: ERROR:django.request:Internal Server Error: /t/tpd12/admin/results/debate/14/new_ballotset/
2016-01-25T09:54:46.431411+00:00 app[web.1]: Traceback (most recent call last):
2016-01-25T09:54:46.431412+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 506, in parse
2016-01-25T09:54:46.431412+00:00 app[web.1]:     compile_func = self.tags[command]
2016-01-25T09:54:46.431413+00:00 app[web.1]: KeyError: 'static'
2016-01-25T09:54:46.431413+00:00 app[web.1]:
2016-01-25T09:54:46.431414+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2016-01-25T09:54:46.431415+00:00 app[web.1]:
2016-01-25T09:54:46.431415+00:00 app[web.1]: Traceback (most recent call last):
2016-01-25T09:54:46.431416+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
2016-01-25T09:54:46.431417+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)
2016-01-25T09:54:46.431417+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
2016-01-25T09:54:46.431418+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2016-01-25T09:54:46.431419+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
2016-01-25T09:54:46.431419+00:00 app[web.1]:     return view_func(request, *args, **kwargs)
2016-01-25T09:54:46.431420+00:00 app[web.1]:   File "/app/utils/views.py", line 25, in foo
2016-01-25T09:54:46.431420+00:00 app[web.1]:     return view_fn(request, request.tournament, *args, **kwargs)
2016-01-25T09:54:46.431421+00:00 app[web.1]:   File "/app/results/views.py", line 232, in new_ballotset
2016-01-25T09:54:46.431422+00:00 app[web.1]:     return r2r(request, template, context)
2016-01-25T09:54:46.431422+00:00 app[web.1]:   File "/app/utils/views.py", line 78, in r2r
2016-01-25T09:54:46.431423+00:00 app[web.1]:     return render_to_response(template, context_instance=rc)
2016-01-25T09:54:46.431424+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/shortcuts.py", line 45, in render_to_response
2016-01-25T09:54:46.431425+00:00 app[web.1]:     using=using)
2016-01-25T09:54:46.431425+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/loader.py", line 114, in render_to_string
2016-01-25T09:54:46.431426+00:00 app[web.1]:     template_name, context, context_instance, dirs, dictionary)
2016-01-25T09:54:46.431427+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/engine.py", line 231, in render_to_string
2016-01-25T09:54:46.431428+00:00 app[web.1]:     t = self.get_template(template_name, dirs)
2016-01-25T09:54:46.431428+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
2016-01-25T09:54:46.431429+00:00 app[web.1]:     template, origin = self.find_template(template_name, dirs)
2016-01-25T09:54:46.431430+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
2016-01-25T09:54:46.431431+00:00 app[web.1]:     name, template_dirs=dirs, skip=skip,
2016-01-25T09:54:46.431431+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/loaders/cached.py", line 39, in get_template
2016-01-25T09:54:46.431432+00:00 app[web.1]:     template_name, template_dirs, skip,
2016-01-25T09:54:46.431433+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
2016-01-25T09:54:46.431433+00:00 app[web.1]:     contents, origin, origin.template_name, self.engine,
2016-01-25T09:54:46.431434+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
2016-01-25T09:54:46.431435+00:00 app[web.1]:     self.nodelist = self.compile_nodelist()
2016-01-25T09:54:46.431435+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 230, in compile_nodelist
2016-01-25T09:54:46.431436+00:00 app[web.1]:     return parser.parse()
2016-01-25T09:54:46.431437+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
2016-01-25T09:54:46.431438+00:00 app[web.1]:     raise self.error(token, e)
2016-01-25T09:54:46.431438+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 512, in parse
2016-01-25T09:54:46.431439+00:00 app[web.1]:     compiled_result = compile_func(self, token)
2016-01-25T09:54:46.431440+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/loader_tags.py", line 267, in do_extends
2016-01-25T09:54:46.431440+00:00 app[web.1]:     nodelist = parser.parse()
2016-01-25T09:54:46.431441+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
2016-01-25T09:54:46.431442+00:00 app[web.1]:     raise self.error(token, e)
2016-01-25T09:54:46.431442+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 512, in parse
2016-01-25T09:54:46.431443+00:00 app[web.1]:     compiled_result = compile_func(self, token)
2016-01-25T09:54:46.431444+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/loader_tags.py", line 241, in do_block
2016-01-25T09:54:46.431445+00:00 app[web.1]:     nodelist = parser.parse(('endblock',))
2016-01-25T09:54:46.431446+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 508, in parse
2016-01-25T09:54:46.431447+00:00 app[web.1]:     self.invalid_block_tag(token, command, parse_until)
2016-01-25T09:54:46.431447+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 562, in invalid_block_tag
2016-01-25T09:54:46.431448+00:00 app[web.1]:     get_text_list(["'%s'" % p for p in parse_until]),
2016-01-25T09:54:46.431449+00:00 app[web.1]: django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 51: 'static', expected 'endblock'. Did you forget to register or load this tag?
```

**Comment by philipbelesky** [comment]
Hey, thanks for the issue. The latest version of `develop` has a fix for this
