### ISSUE TITLE
Error pages are broken

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#315]
This happens when rendering the 404 error page:
```
Traceback (most recent call last):
  File "/home/czlee/git/tabbycat/venv/lib/python3.4/site-packages/django/template/loader_tags.py", line 209, in render
    return template.render(context)
  File "/home/czlee/git/tabbycat/venv/lib/python3.4/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/home/czlee/git/tabbycat/venv/lib/python3.4/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/czlee/git/tabbycat/venv/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/czlee/git/tabbycat/venv/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/czlee/git/tabbycat/utils/templatetags/debate_tags.py", line 105, in render
    args = [context['tournament'].slug]
  File "/home/czlee/git/tabbycat/venv/lib/python3.4/site-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'tournament'
```

On some installations, this has been causing 500 errors, so it displays a 500 when it should display a 404.

I thought error pages should be as basic as possible, to avoid further errors—as in, they should be pretty, but shouldn't rely on anything requiring dynamic lookups. This includes the entire navigation bar, because they rely on `round_url` and `tournament_url` nodes, which is where this error is showing up.

We used to blank out the navigation section on error pages to avoid this problem, but they seem to have been changed to extend the main base.html in 72f9479d2e493f4af21b3549c654277a526c107f. Should they be?

**Comment by philipbelesky** [comment]
I mean from a usability perspective they should include the navigation, but yea at the point that the nav is throwing errors we should forgo it.

**Comment by czlee** [comment]
Wouldn't you need to do the same for the 400, 403 and 500 pages? The root cause is they don't have a tournament associated with them.

**Comment by philipbelesky** [comment]
Err yes; good catch. Fixed now.
