### ISSUE TITLE
1.1.2 actionlog  migration fails in some circumstances

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#386]
Not super clear what's going on here. I've tried re-deploying with a cleared cache without effect. `venue_status` was removed in the 7th `tournament` migration.

Same problem occurs when upgrading the WADL instance, although not with any other site. We should probably get into the habit of rolling out master before issue the release to check for this kind of thing.

No rush to fix; WADL/ACT haven't been having errors recently.

```
Applying actionlog.0013_convert_content_object...Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 170, in __get__
    rel_obj = getattr(instance, self.cache_name)
AttributeError: 'ActionLogEntry' object has no attribute '_round_cache'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column tournaments_round.venue_status does not exist
LINE 1: ...ound"."stage", "tournaments_round"."draw_status", "tournamen...
                                                             ^
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 202, in handle
    targets, plan, fake=fake, fake_initial=fake_initial
  File "/app/.heroku/python/lib/python3.5/site-packages/django/db/migrations/executor.py", line 97, in migrate
    state = self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/db/migrations/executor.py", line 132, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/db/migrations/executor.py", line 237, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/db/migrations/operations/special.py", line 189, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/app/tabbycat/actionlog/migrations/0013_convert_content_object.py", line 19, in convert_content_objects
    value = getattr(action, field)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 179, in __get__
    rel_obj = qs.get()
  File "/app/.heroku/python/lib/python3.5/site-packages/django/db/models/query.py", line 379, in get
    num = len(clone)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/db/models/query.py", line 238, in __len__
    self._fetch_all()
  File "/app/.heroku/python/lib/python3.5/site-packages/django/db/models/query.py", line 1085, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/app/.heroku/python/lib/python3.5/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/app/.heroku/python/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column tournaments_round.venue_status does not exist
LINE 1: ...ound"."stage", "tournaments_round"."draw_status", "tournamen...
                                                             ^
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

**Comment by czlee** [comment]
Hmm, looks like a missing dependency. Will have a look.

**Comment by czlee** [comment]
Can you try that (it's on hotfix/v1.1.3) when you get a chance and let me know how it goes?

Explanation: Since data migrations are manually written they need to specify the relevant dependencies on other migrations—Django automatically includes the most recent migration from the same app, but not those from different apps. So, for example, in this case, it requires `tournaments/0007`, like you say (in fact, I think it requires `tournaments/0014`).

The reason I think this causes failure on some apps and not others is that failure to specify a dependency leaves the order undefined, so Django can run `actionlog/0013` before or after `tournaments/0007`, and probably you don't know in advance which it'll do. (It's also possible that there just weren't any action log entries attached to rounds, but that's unlikely.)

For that reason I guess this is a bit hard to test reliably. Travis will catch any problems with migrations from empty databases, but that won't pick this kind of thing up. Even deploying isn't a guarantee for the same reason, but it's a better check than not doing it, so I agree we should do it.

**Comment by philipbelesky** [comment]
Migrates complete successfully now!
