### ISSUE TITLE
Investigate installation on Bash on Windows

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#420]
The new [Bash on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about) might be nicer than the cumbersome current procedure for installing on Windows (mainly because of PostgreSQL). It's still in beta, so we probably couldn't deprecate the Windows installation instructions yet, but for those who have Windows 10 and are willing to use it, it'd probably be smoother to run.

Currently this is held up slightly by the following issue: https://github.com/Microsoft/BashOnWindows/issues/61

However it sounds like they've been making good progress towards getting PostgreSQL to work with Bash on Windows.

**Comment by czlee** [comment]
The current Bash subsystem uses Trusty (14.04), not Xenial (16.04). There is a third-party package for 14.04 (it's the same one as for 16.04), but it runs into this:
```
$ sudo apt-get install python3.6-dev python3-pip python3.6-venv postgresql-
c-client-9.5 nodejs
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3.6-venv : Depends: python-pip-whl (>= 8.1.0-2) but 1.5.4-1ubuntu4 is to be installed
                  Breaks: python3-pip (< 1.5.6-4) but 1.5.4-1ubuntu4 is to be installed
E: Unable to correct problems, you have held broken packages.
```

Current plan (noting comments at the Microsoft issue above) is to run it with the version of pgAdmin currently on my Windows machine 9.5), and the version of Python currently on the Bash subsystem (Python 3.4).

**Comment by czlee** [comment]
I needed to install `libpq-dev` (from `apt`), I think this probably comes with the server which is why it's not currently in the Linux instructions.

**Comment by czlee** [comment]
Probably best to instruct users to grant create-database privileges to the "tabbycat" user in pgAdmin.

**Comment by czlee** [comment]
I hit this error:

```
$ dj runserver 192.168.56.100:8000
>>> Starting gulp
>>> gulp process on pid 4085

> tabby-cat@ gulp /mnt/c/Users/czlee/git/tabbycat
> gulp "watch" "--development"

Performing system checks...

System check identified no issues (0 silenced).
February 08, 2017 - 05:52:33
Django version 1.10.5, using settings 'settings'
Starting development server at http://192.168.56.100:8000/
Quit the server with CONTROL-C.
(node:4104) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
GULP: Building for development
[05:52:42] Using gulpfile /mnt/c/Users/czlee/git/tabbycat/Gulpfile.js
[05:52:42] Starting 'fonts-compile'...
[05:52:42] Finished 'fonts-compile' after 88 ms
[05:52:42] Starting 'styles-compile'...
[05:52:42] Finished 'styles-compile' after 15 ms
[05:52:42] Starting 'js-vendor-compile'...
[05:52:42] Finished 'js-vendor-compile' after 5.39 ms
[05:52:42] Starting 'js-compile'...
[05:52:42] Finished 'js-compile' after 7.55 ms
[05:52:42] Starting 'js-browserify'...
[05:52:56] Finished 'js-browserify' after 14 s
[05:52:59] Starting 'build'...
[05:52:59] Finished 'build' after 7 μs
[05:52:59] Starting 'watch'...
[05:52:59] 'watch' errored after 248 ms
[05:52:59] Error: watch /mnt/c/Users/czlee/git/tabbycat/tabbycat/templates/scss/ EPERM
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at Gaze._watchDir (/mnt/c/Users/czlee/git/tabbycat/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)
    at /mnt/c/Users/czlee/git/tabbycat/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/mnt/c/Users/czlee/git/tabbycat/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/mnt/c/Users/czlee/git/tabbycat/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:66:3)
    at Gaze._initWatched (/mnt/c/Users/czlee/git/tabbycat/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:354:10)
    at Gaze.add (/mnt/c/Users/czlee/git/tabbycat/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:177:8)
    at new Gaze (/mnt/c/Users/czlee/git/tabbycat/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:74:10)
```

It doesn't appear to be fatal though? @philipbelesky, any ideas? I assume this just means it won't live-track code updates in development mode?

Otherwise, it works! I could write up quick instructions for 1.2. Since installing pgAdmin isn't that cumbersome, I think I'll just wait for Microsoft/BashOnWindows#61 to be closed before trying also to install the PostgreSQL server on the subsystem.

**Comment by philipbelesky** [comment]
I wonder if the error goes away if you do a `collectstatic` then use the `waitress` server? We could also try bumping that `gaze` module (or the livereload module that drew it in.

**Comment by czlee** [comment]
This still shows up in `collectstatic`:
```
(node:301) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
```

The less graceful error doesn't happen, but when I run the `waitress` server I don't see anything at all (e.g. I don't see the standard logging messages that Django does), so I'm not sure if it's not happening or if it's just being suppressed?
